template: |
  ## What’s Changed
  $CHANGES
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "⚙️ Config"
    label: "config"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "🔧 Dependency updates"
    label: "dependencies"
